export const mockDataNav = {
  data: {
    id: 1,
    createdAt: "2024-05-03T08:03:28.356Z",
    updatedAt: "2025-04-26T08:02:58.091Z",
    publishedAt: "2024-05-03T08:03:46.368Z",
    locale: "en",
    documentId: "jt6fx0n2o49sf9wxh4p9146b",
    navigation: {
      id: 1,
      myText: "myText test",
      items: [
        {
          id: 1,
          label: "Fallback",
        },
        {
          id: 18,
          href: "/de",
          label: "DE",
          target: null,
          isExternal: false,
          page: null,
        },
        {
          id: 8,
          href: null,
          label: "Home",
          target: null,
          isExternal: false,
          page: {
            id: 1,
            title: "Home",
            slug: "/",
            createdAt: "2024-05-02T14:44:40.027Z",
            updatedAt: "2025-04-26T08:37:28.688Z",
            publishedAt: "2024-05-03T07:43:14.210Z",
            locale: "en",
            documentId: "go03i9e4vusvq3vv0673nwft",
          },
        },
        {
          id: 9,
          href: null,
          label: "About",
          target: null,
          isExternal: false,
          page: {
            id: 3,
            title: "About",
            slug: "/about",
            createdAt: "2024-06-12T08:06:43.996Z",
            updatedAt: "2025-04-26T08:37:42.360Z",
            publishedAt: "2024-06-12T08:06:50.864Z",
            locale: "en",
            documentId: "tdy4ku2393v732p0uub3qsn6",
          },
        },
        {
          id: 22,
          href: "/api-hello-test",
          label: "/api/hello Test",
          target: null,
          isExternal: false,
          page: null,
        },
        {
          id: 21,
          href: "/auth/signin",
          label: "Auth Provider SignIn",
          target: null,
          isExternal: false,
          page: null,
        },
        {
          id: 17,
          href: "/not-found-link",
          label: "Not found",
          target: null,
          isExternal: false,
          page: null,
        },
        {
          id: 16,
          href: "https://developer.mozilla.org/en-US/docs/Web/HTML",
          label: "Extern Link",
          target: "_blank",
          isExternal: false,
          page: null,
        },
      ],
    },
  },
  meta: {},
};
