export const mockDataGenerateMetadata = {
  data: [
    {
      id: 1,
      title: "Home",
      slug: "/",
      createdAt: "2024-05-02T14:44:40.027Z",
      updatedAt: "2025-04-26T08:37:28.688Z",
      publishedAt: "2024-05-03T07:43:14.210Z",
      locale: "en",
      documentId: "go03i9e4vusvq3vv0673nwft",
      seo: {
        id: 1,
        metaTitle: "Home metaTitle",
        metaDescription: "Home metaDescription",
        keywords: null,
        metaRobots: null,
        structuredData: null,
        metaViewport: null,
        canonicalURL: null,
        metaImage: {
          id: 26,
          name: "blck.jpg",
          alternativeText: null,
          caption: null,
          width: 4852,
          height: 2746,
          formats: {
            thumbnail: [Object],
            xs_webp: [Object],
            sm_webp: [Object],
            md_webp: [Object],
            lg_webp: [Object],
            original_webp: [Object],
            xl_webp: [Object],
          },
          hash: "blck_248144eb23",
          ext: ".jpg",
          mime: "image/jpeg",
          size: 79.39,
          url: "/uploads/blck_248144eb23.jpg",
          previewUrl: null,
          provider: "local",
          provider_metadata: null,
          createdAt: "2024-06-12T08:26:58.583Z",
          updatedAt: "2024-06-12T16:12:21.285Z",
          documentId: "bmoiqivfvuwkxwiq8nx5nmkk",
          publishedAt: "2025-04-29T16:02:15.252Z",
        },
        metaSocial: [],
      },
    },
  ],
  meta: { pagination: { page: 1, pageSize: 25, pageCount: 1, total: 1 } },
};
